package.json
src/api.ts
src/utils.ts
yarn.lock

Fixes https://github.com/snapshot-labs/snapshot-relayer/issues/4

Fix hash with safe version 1.1.1

---

src/api.ts

Fixes https://github.com/snapshot-labs/snapshot-relayer/issues/3

Add test route

---

package.json
yarn.lock

There is an error with nodemon older version (i think only on windows) that doesn't allow the server to restart when there is a change in code

Update nodemon and move to dev deps

---

src/utils.ts

Same as https://github.com/snapshot-labs/stamp/commit/e91ab914bbc34358bf3b17f3fcc778d85d70366b

Use brovider

---

src/api.ts
src/check.ts
src/schema.sql
src/subgraphs.json
yarn.lock

Add support for multiple networks

---

src/api.ts

Fixes https://github.com/snapshot-labs/snapshot-relayer/issues/32

Add get messages route

---

src/check.ts
src/subgraphs.json

Process sigs for polygon network

---

.eslintrc
src/api.ts
src/check.ts
src/constants.json

Fixes https://github.com/snapshot-labs/snapshot-relayer/issues/46

EIP-712 messages with Safe

---

src/api.ts
src/check.ts
src/constants.json

Fixes https://github.com/snapshot-labs/snapshot-relayer/issues/59

Remove personal sign

---

src/api.ts

Add commit hash

---

src/check.ts

Add support to Arbitrum safe

---

src/api.ts
src/check.ts

Support goerli and bnb voting

---

src/check.ts

Right now we delete the message irrespective the result, with this change we won't delete them if it is network/node related issue

Prevent deletion if it is a network issue

---

.github/workflows/create-sentry-release.yml
package.json
src/api.ts
src/check.ts
src/index.ts
yarn.lock

- Install sentry and capture error from catch block
- Add CI workflow to upload sourcemaps on deploy

feat: add sentry

---

.github/workflows/lint.yml
package.json

chore: add lint to CI

---

.github/dependabot.yml

Relax dependabot rules to auto-update all package from @snapshot-labs

chore: auto update all packages from same org

---

tsconfig.json

Output sourcemaps on build, and upload them to Sentry

chore: output sourcemaps on build

---

package.json
src/check.ts
yarn.lock

`node-fetch` is used, without being explicitly defined in the dependencies.
- Explicitly add `node-fetch` as required dependency
- Add `node-fetch` to dependency
- N/A

fix: fix missing dependency

---

package.json
src/check.ts
yarn.lock

Add more contexts data when capturing errors

chore: capture more error contexts

---

src/constants.json

Change to new URL, More details: https://discord.com/channels/955773041898573854/1030772407226601522/1175036485842509884

fix: update hub testnet URL

---

src/check.ts

Safe now supports Sepolia but not Goerli

fix: Add support for sepolia and remove support for goerli

---

src/check.ts

Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/319

fix: Update error message while fetching block
